//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "house_aggregate")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub house_id: String,
    pub community_id: String,
    pub house_address: String,
    pub publish_at: Option<DateTimeUtc>,
    pub unpublish_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
