//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod community_aggregate;
pub mod community_query;
pub mod house_aggregate;
pub mod house_query;
pub mod owner;
pub mod owner_query;
