//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::community_aggregate::Entity as CommunityAggregate;
pub use super::house_aggregate::Entity as HouseAggregate;
pub use super::owner::Entity as Owner;
