//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

#[allow(unused_imports)]
pub use super::community_aggregate::Entity as CommunityAggregate;
pub use super::community_query::Entity as CommunityQuery;
pub use super::house_aggregate::Entity as HouseAggregate;
pub use super::house_query::Entity as HouseQuery;
pub use super::owner::Entity as Owner;
pub use super::owner_query::Entity as OwnerQuery;
