POST http://localhost:3001/api/role/update
Content-Type: application/json

{
  "id": "7c48f89a-9cf2-4c79-b8f5-ac2b5cd2991e",
  "name": "admin",
  "description": "超级管理员111",
  "permissions": [
    {
      "resouce": "user",
      "permission": "create"
    },
    {
      "resouce": "user",
      "permission": "delete"
    },
    {
      "resouce": "user",
      "permission": "update"
    }
  ]
}