POST http://localhost:9001/api/user_system/role/create
Content-Type: application/json


{
    "name": "Administrator",
    "description": "普通管理员",
    "permissions": [
        {
            "source": "^/api/user/*",
            "action": "POST"
        },
        {
            "source": "^/api/role/*",
            "action": "POST"
        }
    ]
}

