
POST http://localhost:9001/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

# "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNTYyZTAzMTEtOWJkMy00YjJmLWJkZDMtNmEwZjhjY2U5N2RhIiwidXNlcm5hbWUiOiJhZG1pbiIsInJ1bGVzIjpbXSwiZXhwIjoxNzUxMDgwMTUyLCJpYXQiOjE3NTA5OTM3NTJ9.T6UHrpkorW0SAkkMoYrgWU0CdTdTdqHmjkFzOLaiPAg"