
GET http://localhost:9001/api/user_system/role/list?page=1&page_size=10
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNDkzNjVkZDQtOWRkYS00NDI1LTk4ZGQtMjAxNWRlMDY3OTZiIiwidXNlcm5hbWUiOiJhZG1pbiIsInJ1bGVzIjpbIjlmZjYxNTkyLTc1OTYtNDI3NS1hYTU3LTUyZjRmMzI2ODhlZSJdLCJleHAiOjE3NTMwMjI1MTMsImlhdCI6MTc1MjkzNjExM30.cUQoFi-nwzYvY4mRmphQciulHu1G87BYEZxtpo6nX1M
