POST http://localhost:9001/api/role/update
Content-Type: application/json

{
  "id": "c2877548-3496-46fb-8b91-1fc55cabd3cb",
  "name": "admin",
  "description": "超级管理员",
  "permissions": [
    {
      "resouce": "/api/role/create",
      "permission": "POST"
    },
    {
      "resouce": "/api/role/delete",
      "permission": "POST"
    },
    {
      "resouce": "/api/role/update",
      "permission": "POST"
    },
    {
      "resouce": "/api/user/register",
      "permission": "POST"
    }
  ]
}