POST http://localhost:3001/api/community/update
Content-Type: application/json

{
  "community_id": "03137937-20b1-4a72-b504-e2a34e1721cc",
  "name": "New Community",
  "description": "A place for new ideas",
  "address": "123 Main St 444",
  "city": "New York",
  "year_built": 2023,
  "community_type": "residential"
}