//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod casbin_rules;
pub mod permission;
pub mod permission_role;
pub mod role_aggregate;
pub mod role_user;
pub mod sea_orm_active_enums;
pub mod user_aggregate;
pub mod user_details_read;
pub mod user_login_history;
pub mod user_operation_log;
