//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::user_aggregate::Entity as UserAggregate;
pub use super::user_details_read::Entity as UserDetailsRead;
pub use super::user_login_history::Entity as UserLoginHistory;
pub use super::user_operation_log::Entity as UserOperationLog;
