//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_login_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: String,
    pub username: String,
    pub status: Status,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub login_at: DateTime,
    pub fail_reason: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
