# k8s-deploy.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: meida
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-system
  namespace: meida
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-system
  template:
    metadata:
      labels:
        app: user-system
    spec:
      containers:
        - name: user-system
          image: registry.cn-hangzhou.aliyuncs.com/tongts/user_system-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # 如果需要配置环境变量，可以在这里添加
            - name: USER_SYSTEM_PORT
              value: "8080"
            - name: HOST
              value: "0.0.0.0"
            - name: MINIO_URL
              value: "http://192.168.2.10:9000"
            - name: ACCESS_KEY_ID
              value: "minioadmin"
            - name: SECRET_ACCESS_KEY
              value: "minioadmin"
            - name: USER_SYSTEM_DATABASE_URL
              value: "mysql://root:123456@192.168.2.10/meida"
          resources:
            requests:
              cpu: "250m" # 0.25 核心
              memory: "256Mi" # 256 MB
            limits:
              cpu: "500m" # 最大 0.5 核心
              memory: "512Mi" # 最大 512 MB
---
apiVersion: v1
kind: Service
metadata:
  name: user-system-svc
  namespace: meida
spec:
  selector:
    app: user-system
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
