
POST http://localhost:3001/api/user/update
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTkyODVhZmQtNmVlMC00ODZjLTg2OGEtMzlhM2Q0MzAzNWViIiwidXNlcm5hbWUiOiJhZG1pbiIsInJ1bGVzIjpbImMyODc3NTQ4LTM0OTYtNDZmYi04YjkxLTFmYzU1Y2FiZDNjYiJdLCJleHAiOjE3NTEwODk5OTQsImlhdCI6MTc1MTAwMzU5NH0.UqpbtlHdf-b-3Q62yTySg-u3rkMeNIGiV4-pYwMDJU4

{
  "id": "99285afd-6ee0-486c-868a-39a3d43035eb",
  "email": "1111"
}

