[package]
name = "event_bus"
version = "0.1.0"
edition = "2021"

[dependencies]
base64ct="<1.8.0"
async-trait = { version = "0.1" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"

[lib]
path = "src/lib.rs"
