[package]
name = "event_bus"
version = "0.1.0"
edition = "2021"

[dependencies]
base64ct="<1.8.0"
async-trait = {  workspace = true }
tokio = { workspace = true }
futures = { workspace = true }

[lib]
path = "src/lib.rs"
