POST http://localhost:9002/api/community/update
Content-Type: application/json

{
  "community_id": "3609a301-3b8c-4d95-81b6-236178d964b9",
  "name": "New Community",
  "description": "A place for new ideas",
  "address": "888888",
  "city": "New York",
  "year_built": 2024,
  "community_type": "residential"
}