//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod event_record;
pub mod permissions_detail;
pub mod prelude;
pub mod role_aggregate;
pub mod role_detail_read_model;
pub mod sea_orm_active_enums;
pub mod user_aggregate;
pub mod user_login_history;
pub mod user_operation_log;
pub mod user_query;
