name: Deploy with Docker Swarm

on:
  push:
    branches:
      - master # 你要触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 把你当前仓库的代码 checkout（拉取）到 GitHub Actions 的 runner 环境里

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # 在 GitHub Actions 的 Runner 上安装并配置 Docker Buildx，让你能够使用 docker buildx build 来构建镜像。

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_REGISTRY }}/tongts/domus-service:v1 --push -f domus/Dockerfile .
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_REGISTRY }}/tongts/user_system-service:v1 --push -f user_system/Dockerfile .

      - name: Deploy to Swarm
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /${{ secrets.SSH_USER }}/www/user_system
            docker stack deploy -c docker-stack.yml meida-web
