[package]
name = "domus"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
event_bus = { workspace = true }
uuid = { workspace = true }